/*
389. Find the Difference
Easy
3.9K
429
company
IBM
company
Google
company
Amazon

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:

Input: s = "", t = "y"
Output: "y"

 

Constraints:

    0 <= s.length <= 1000
    t.length == s.length + 1
    s and t consist of lowercase English letters.

Accepted
506.8K
Submissions
849.6K
Acceptance Rate
59.6%
Seen this question in a real interview before?
1/4
Yes
No
Discussion (27)
Similar Questions
Single Number
Easy
Related Topics
Hash Table
String
Bit Manipulation
Sorting
*/
class Solution {
    public char findTheDifference(String s, String t) {
        char the_difference = 0;

        for(int i = 0; i < s.length(); i++)     the_difference ^= s.charAt(i);
        for(int i = 0; i < t.length(); i++)     the_difference ^= t.charAt(i);

        return the_difference;
    }
}